config/routes.rb
Rails.application.routes.draw do



  namespace :public do
    get 'attachments/destroy'
  end
 devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}


devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

 scope module: :public do
  root 'homes#top'
  get '/about' => 'homes#about'
  get 'users/my_page/:id' => 'users#show', as:'users_my_page'
  get 'users/information/edit' => 'users#edit'
  patch 'users/information' => 'users#update'
  get 'users/confirm_withdraw' => 'users#confirm_withdraw'
  delete 'users/withdraw' => 'users#withdraw'

  resources :attachments, controller: 'attachments', only: %i[destroy]

  resources :reviews do
    resource :review_favorites, only: [:create, :destroy]
      post 'create_mini' => 'review_favorites#create_mini', as: 'create_mini'
      delete 'destroy_mini' => 'review_favorites#destroy_mini', as: 'destroy_mini'
    resources :review_comments, only: [:create, :update, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :bookmarks, only: [:index, :create, :destroy]

   resources :users do
    resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      post 'create_mini' => 'relationships#create_mini', as: 'create_mini'
      delete 'destroy_mini' => 'relationships#destroy_mini', as: 'destroy_mini'
    end
  end



  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end


  namespace :admin do

    resources :reviews, only: [:index, :show, :destroy] do
     resources :review_comments, only: [:destroy]
    end

    resources :users, only: [:index, :show, :destroy]
    resources :facility_categories, only: [:index, :create, :update, :destroy]

  end




  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/facility_category.rb
class FacilityCategory < ApplicationRecord
  has_many :review_facility_categories, dependent: :destroy
  has_many :reviews, through: :review_facility_categories
end

app/controllers/admin/facility_categories_controller.rb
class Admin::FacilityCategoriesController < ApplicationController
   before_action :authenticate_admin!

  def index
    @facility_categories = FacilityCategory.all
    @facility_category = FacilityCategory.new
  end

  def create
    @facility_category = FacilityCategory.new(facility_category_params)
    @facility_category.save
    flash[:notice] = "カテゴリーを作成しました。"
    redirect_to admin_facility_categories_path
  end

  def destroy
    @facility_category = FacilityCategory.find(params[:id])
    @facility_category.destroy
    flash[:notice] = "カテゴリーを削除しました。"
    redirect_to admin_facility_categories_path
  end

  private

  def facility_category_params
    params.require(:facility_category).permit(:category_name)
  end

end

app/helpers/admin/facility_categories_helper.rb
module Admin::FacilityCategoriesHelper
end

app/views/admin/facility_categories/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 mx-auto">
    <br>
    <br>
    <div class="row">
      <div class="col-6">
        <h4 class="underlined-text">カテゴリー一覧</h4>
      </div>
    </div>
    <br>
    <%= form_with model: @facility_category,url: admin_facility_categories_path, method: :post do |f| %>
      <div class="row">
        <div class="col-1"></div>
        <div class="col-3">
          <h6>カテゴリー名</h6>
        </div>
        <div class="col-6">
          <%= f.text_field :category_name%>
          <%= f.submit "新規登録", class: "edit-btn btn-outline-2" %>
          <% end %>
        </div>
        <br>
        <%= flash[:facility_category] %>
        <br>
        <table class="table">
          <% @facility_categories.each do |facility_category| %>
            <tbody>
              <tr>
                <td style="height: 80px; width: 10%; vertical-align: middle;"></td>
                <td style="height: 80px; width: 50%; vertical-align: middle; color: #6f4d3e;"><%= facility_category.category_name %></td>
                <td style="height: 80px; width: 40%; vertical-align: middle;"><%= link_to "削除", admin_facility_category_path(facility_category.id), method: :delete, class: "btn btn-sm btn-danger edit-btn", "data-confirm" => "本当に削除しますか？"  %></td>
              </tr>
            </tbody>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>
<br>
<br>