config/routes.rb
Rails.application.routes.draw do



  namespace :public do
    get 'attachments/destroy'
  end
 devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}


devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

 scope module: :public do
  root 'homes#top'
  get '/about' => 'homes#about'
  get 'users/my_page/:id' => 'users#show', as:'users_my_page'
  get 'users/information/edit' => 'users#edit'
  patch 'users/information' => 'users#update'
  get 'users/confirm_withdraw' => 'users#confirm_withdraw'
  delete 'users/withdraw' => 'users#withdraw'

  resources :attachments, controller: 'attachments', only: %i[destroy]

  resources :reviews do
    resource :review_favorites, only: [:create, :destroy]
      post 'create_mini' => 'review_favorites#create_mini', as: 'create_mini'
      delete 'destroy_mini' => 'review_favorites#destroy_mini', as: 'destroy_mini'
    resources :review_comments, only: [:create, :update, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :bookmarks, only: [:index, :create, :destroy]

   resources :users do
    resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      post 'create_mini' => 'relationships#create_mini', as: 'create_mini'
      delete 'destroy_mini' => 'relationships#destroy_mini', as: 'destroy_mini'
    end
  end



  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end


  namespace :admin do

    resources :reviews, only: [:index, :show, :destroy] do
     resources :review_comments, only: [:destroy]
    end

    resources :users, only: [:index, :show, :destroy]
    resources :facility_categories, only: [:index, :create, :update, :destroy]

  end




  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
   before_action :authenticate_admin!

  def index
    @reviews = Review.page(params[:page]).order(created_at: :desc)
  end

  def show
    @review = Review.find(params[:id])
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    flash[:notice] = "レビューを削除しました。"
    redirect_to admin_reviews_path
  end


 private

  def review_params
    params.require(:review).permit(:facility_name, :text, :rating, :post_code, :address, image: [])
  end

end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/views/admin/reviews/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="scroll_area pt-5">
      <div class="pb-4">
        <h4 class="underlined-text">レビュー一覧</h4>
      </div>
      <table class='table'>
        <thead class="thead-light-1">
          <tr>
            <th style="height: 50px; color: #6f4d3e;">　　　画像</th>
            <th style="height: 50px; color: #6f4d3e;">施設名</th>
            <th style="height: 50px; color: #6f4d3e;">投稿者</th>
            <th style="height: 50px; color: #6f4d3e;">コメント</th>
            <th style="height: 50px; color: #6f4d3e;"></th>
          </tr>
        </thead>
        <tbody>
          <% @reviews.each do |review| %>
            <tr>
              <td>
                <% count = 1 %>
                <% if review.image.attached? %>
                  <% review.image.each do |image| %>
                    <% if count == 1 %>
                      <%= image_tag image.variant(resize_to_fill: [120, 120]) %>
                    <% end %>
                    <% count += 1 %>
                  <% end %>
                <% else %>
                  <%= image_tag asset_path("review_no_image.jpg"), size: "150x110" %>
                <% end %>
              </td>
              <td style="height: 60px; vertical-align: middle; color: #6f4d3e;"><%= review.facility_name %></td>
              <td style="height: 60px; vertical-align: middle; color: #6f4d3e;"><%= review.user.name %></td>
              <td style="height: 60px; vertical-align: middle; color: #6f4d3e;">　<%= review.review_comments.count %>件</td>
              <td style="height: 60px; vertical-align: middle;"><%= link_to "詳細", admin_review_path(review), class: "btn edit-btn", style: "background-color: #ff7f50; color: #FFF;", 'data-turbolinks': false %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<br>
<br>
<div class="paginate">
  <%= paginate @reviews %>
</div>

app/views/admin/reviews/show.html.erb
<br>
<br>
<div class="container">
  <div class="row">
    <div class="col-10 mx-auto">

      <h4 class="underlined-text">レビュー詳細</h4>

      <div class='container px-5 px-sm-0'>
        <div class='row'>
          <div class='col-md-11'>
          <br>
            <div class="row">
              <div class="col-md-11 mb-4 d-flex flex-row-reverse">
                <%= link_to "削除", admin_review_path, method: :delete, class: "btn btn-danger edit-btn", "data-confirm" => "本当に削除しますか？"  %>
              </div>
            </div>

            <table class="table">
              <tbody>
                <tr>
                  <td style="height: 75px; width: 40%; vertical-align: middle; color: #6f4d3e;">投稿者</td>
                  <td class="admin-user-name", style="height: 75px; width: 60%; vertical-align: middle; color: #6f4d3e;"><%= link_to @review.user.name, admin_user_path(@review.user) %></td>
                </tr>

                <tr>
                  <td style="height: 75px; width: 40%; vertical-align: middle; color: #6f4d3e;">施設名</td>
                  <td style="height: 75px; width: 60%; vertical-align: middle; color: #6f4d3e;"><%= @review.facility_name %></td>
                </tr>

                <tr>
                  <td style="height: 75px; width: 40%; vertical-align: middle; color: #6f4d3e;">レビュー</td>
                  <td style="height: 75px; width: 60%; vertical-align: middle; color: #6f4d3e;"><%= @review.text %></td>
                </tr>

                <tr>
                  <td style="height: 75px; width: 40%; vertical-align: middle; color: #6f4d3e;">評価</td>
                  <td style="height: 75px; width: 60%; vertical-align: middle; color: #6f4d3e;">
                    <div id="post_raty"></div>
                    <script>
                      let elem = document.querySelector('#post_raty');
                      let opt = {
                        //path: '/assets',
                        starOn: "<%= asset_path('star-on.png') %>",
                        starOff: "<%= asset_path('star-off.png') %>",
                        starHalf: "<%= asset_path('star-half.png') %>",
                        scoreName: 'review[rating]',
                        score: <%= j(@review.rating ? @review.rating : 0) %>,
                        readOnly: true
                       };
                      raty(elem,opt);
                    </script>
                  </td>
                </tr>

                <tr>
                  <td style="height: 75px; width: 40%; vertical-align: middle; color: #6f4d3e;">カテゴリー</td>
                  <td style="height: 75px; width: 60%; vertical-align: middle; color: #6f4d3e;"><%= @review.facility_categories.pluck(:category_name).join(",") %></td>
                </tr>

                <tr>
                  <td style="height: 75px; width: 40%; vertical-align: middle; color: #6f4d3e;">郵便番号</td>
                  <td style="height: 75px; width: 60%; vertical-align: middle; color: #6f4d3e;"><%= @review.post_code %></td>
                </tr>

                <tr>
                  <td style="height: 75px; width: 40%; vertical-align: middle; color: #6f4d3e;">住所</td>
                  <td style="height: 75px; width: 60%; vertical-align: middle; color: #6f4d3e;"><%= @review.address %></td>
                </tr>

                <tr>
                  <td style="height: 75px; width: 40%; color: #6f4d3e;">画像</td>
                  <td style="height: 75px; width: 60%">
                    <div class="d-flex flex-wrap">
                      <% if @review.image.attached? %>
                        <% @review.image.each do |image| %>
                          <%= image_tag image.variant(resize: '230x230') %>
                        <% end %>
                      <% end %>
                    </div>
                  </td>
                </tr>

                <tr>
                  <td style="height: 75px; width: 40%; color: #6f4d3e;">コメント</td>
                  <td>
                    <table class="table">
                      <tbody>
                        <% @review.review_comments.each do |review_comment| %>
                        <tr>
                          <td style="color: #6f4d3e;">
                            投稿者:  <%= link_to review_comment.user.name, admin_user_path(review_comment.user), class: "link" %><br>
                            <%= simple_format review_comment.text %>
                          </td>
                          <td width="80">
                            <%= link_to "削除", admin_review_review_comment_path(@review, review_comment), method: :delete, class: "btn btn-sm btn-danger", "data-confirm" => "本当に削除しますか？"  %>
                          </td>
                        <% end %>
                        </tr>
                      </tbody>
                    </table>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<br>
<br>