config/routes.rb
Rails.application.routes.draw do



  namespace :public do
    get 'attachments/destroy'
  end
 devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}


devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

 scope module: :public do
  root 'homes#top'
  get '/about' => 'homes#about'
  get 'users/my_page/:id' => 'users#show', as:'users_my_page'
  get 'users/information/edit' => 'users#edit'
  patch 'users/information' => 'users#update'
  get 'users/confirm_withdraw' => 'users#confirm_withdraw'
  delete 'users/withdraw' => 'users#withdraw'

  resources :attachments, controller: 'attachments', only: %i[destroy]

  resources :reviews do
    resource :review_favorites, only: [:create, :destroy]
      post 'create_mini' => 'review_favorites#create_mini', as: 'create_mini'
      delete 'destroy_mini' => 'review_favorites#destroy_mini', as: 'destroy_mini'
    resources :review_comments, only: [:create, :update, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :bookmarks, only: [:index, :create, :destroy]

   resources :users do
    resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      post 'create_mini' => 'relationships#create_mini', as: 'create_mini'
      delete 'destroy_mini' => 'relationships#destroy_mini', as: 'destroy_mini'
    end
  end



  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end


  namespace :admin do

    resources :reviews, only: [:index, :show, :destroy] do
     resources :review_comments, only: [:destroy]
    end

    resources :users, only: [:index, :show, :destroy]
    resources :facility_categories, only: [:index, :create, :update, :destroy]

  end




  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_admin_signed_in.html.erb
<li><%= link_to '会員一覧', admin_users_path, class: 'nav-link text-light mx-4 px-4', style: 'background-color: #937B69;' %></li>
<li><%= link_to 'レビュー', admin_reviews_path ,class:'nav-link text-light mx-4 px-4', style: 'background-color: #937B69;' %></li>
<li><%= link_to 'カテゴリー', admin_facility_categories_path ,class:'nav-link text-light mx-4 px-4', style: 'background-color: #937B69;' %></li>
<li><%= link_to 'ログアウト', destroy_admin_session_path, method: :delete ,class:'nav-link text-light mx-4 px-4', style: 'background-color: #937B69;' %></li>

app/views/layouts/_sign_out.html.erb
<li><%= link_to '新規登録', new_user_registration_path, class:'nav-link text-light mx-4 px-4 btn', style: 'background-color: #ff7f50;' %></li>
<li><%= link_to 'ログイン', new_user_session_path, class:'nav-link text-light mx-4 px-4 btn', style: 'background-color: #ff7f50' %></li>
<li><%= link_to 'レビュー', reviews_path, class:'nav-link text-light mx-4 px-4 btn', style: 'background-color: #ff7f50;' %></li>
<li><%= link_to 'About', about_path, class:'nav-link text-light mx-4 px-4 btn', style: 'background-color: #ff7f50;' %></li>

app/views/layouts/_user_signed_in.html.erb
<li><%= link_to 'マイページ', users_my_page_path(current_user) ,class:'nav-link text-light mx-4 px-4 btn', style: 'background-color: #ff7f50;' %></li>
<li><%= link_to '新規投稿' , new_review_path, class:'nav-link text-light mx-4 px-4 btn', style: 'background-color: #ff7f50;', 'data-turbolinks': false %></li>
<li><%= link_to 'レビュー', reviews_path, class:'nav-link text-light mx-4 px-4 btn', style: 'background-color: #ff7f50;' %></li>
<li><%= link_to 'お気に入り', bookmarks_path, class:'nav-link text-light mx-4 px-4 btn', style: 'background-color: #ff7f50;' %></li>
<li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:'nav-link text-light mx-4 px-4 btn', style: 'background-color: #ff7f50;' %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>With dog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/1a85cb0c49.js" crossorigin="anonymous"></script>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css" rel="stylesheet">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/js/lightbox.min.js" type="text/javascript"></script>
  </head>

  <body>
    <header class="mb-4 bg-white border-bottom border-dark">
      <nav class="navbar navbar-expand-lg navbar-dark p-2 ">
        <div class="container">
           <div class="logo-image">
             <%= link_to root_path do %>
              <%= image_tag 'logo.jpg', :size => '200x200', :alt => 'ロゴ' %>
            <% end %>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="navbar-collapse collapse show" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <%= render 'layouts/user_signed_in' %>
              <% elsif admin_signed_in? %>
                <%= render 'layouts/admin_signed_in' %>
              <% else %>
                <%= render 'layouts/sign_out' %>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
      <div class="container">
        <div class="row">
          <div class="col-sm-12 col-md-10 col-lg-10 mx-auto">
          </div>
        </div>
      </div>
    </header>
    <% if notice %>
      <div class="alert aleart-warning text-center m-0">
        <%= notice %>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert aleart-warning text-center m-0">
        <%= alert %>
      </div>
    <% end %>
    <%= yield %>
    <footer class="bg-white border-top border-dark pt-5 pb-5 mt-4">
      <div class="container">
        <div class="row">
          <div class="col-3 mx-auto">
            <h3 class="logo">With dog</h3>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>